import type {
  MercadoLivreAnalysisSummary,
  MercadoLivreProductPerformance,
  MercadoLivreTopProductsAnalysisResponse,
} from '@/types/api';

/**
 * Dados fictícios para demonstração da tela de lucratividade.
 *
 * Modelados a partir de uma análise real exportada em planilha (Mercado
 * Livre, agosto de 2026), mas com valores de produto que servem apenas de
 * exemplo — não vêm da API e não devem ser tratados como leitura de uma loja
 * real. Útil para apresentar a tela antes da leitura de lucro em produção
 * sair da validação interna (ver `AdminOnlyRoute` em `AppRoutes.tsx`).
 */

const MOCK_PRODUCTS: MercadoLivreProductPerformance[] = [
  {
    itemFullId: 'MLB5096194919',
    itemId: null,
    title: 'Kit 4 Top Feminino Sutia Sem Costura Azul Bojo Sustentação Azul P/M',
    pictureUrl: null,
    unitPriceAverage: 78.62,
    quantitySold: 1,
    ordersCount: 1,
    grossRevenue: 78.62,
    totalSaleFees: 14.94,
    netRevenue: 63.68,
    proportionalShippingCost: 54.24,
    proportionalBillingCharges: 0,
    cmvUnit: 38.4,
    totalCogs: 38.4,
    totalCosts: 107.58,
    grossProfit: 25.28,
    grossMarginPercent: 32.15,
    netProfit: -32.1,
    netMarginPercent: -40.83,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB4899224859',
    itemId: null,
    title: 'Kit 3 Pares Meia Soquete Cano Curto Confortável Cor Sortida',
    pictureUrl: null,
    unitPriceAverage: 16.18,
    quantitySold: 2,
    ordersCount: 2,
    grossRevenue: 32.35,
    totalSaleFees: 5.7,
    netRevenue: 26.65,
    proportionalShippingCost: 37.08,
    proportionalBillingCharges: 0,
    cmvUnit: 3.12,
    totalCogs: 6.24,
    totalCosts: 49.02,
    grossProfit: 20.41,
    grossMarginPercent: 63.09,
    netProfit: -17.96,
    netMarginPercent: -55.52,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB7526690034',
    itemId: null,
    title:
      'Kit 3 Cueca Box Masculina Uomo Adulto Elástico Várias Cores Diversas P/M',
    pictureUrl: null,
    unitPriceAverage: 33.75,
    quantitySold: 1,
    ordersCount: 1,
    grossRevenue: 33.75,
    totalSaleFees: 4.72,
    netRevenue: 29.03,
    proportionalShippingCost: 19.14,
    proportionalBillingCharges: 0,
    cmvUnit: 11.55,
    totalCogs: 11.55,
    totalCosts: 35.41,
    grossProfit: 17.48,
    grossMarginPercent: 51.79,
    netProfit: -3.01,
    netMarginPercent: -8.92,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB4960747659',
    itemId: null,
    title: 'Calça Moletom Masculina Flanelada Com Bolso Confortável',
    pictureUrl: null,
    unitPriceAverage: 51.12,
    quantitySold: 1,
    ordersCount: 1,
    grossRevenue: 51.12,
    totalSaleFees: 7.16,
    netRevenue: 43.96,
    proportionalShippingCost: 8.05,
    proportionalBillingCharges: 0,
    cmvUnit: 26.9,
    totalCogs: 26.9,
    totalCosts: 42.11,
    grossProfit: 17.06,
    grossMarginPercent: 33.37,
    netProfit: 6.97,
    netMarginPercent: 13.63,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB5096218851',
    itemId: null,
    title:
      'Kit 2 Top Feminino Sutia Sem Costura Bege Bojo Sustentação Bege P/M',
    pictureUrl: null,
    unitPriceAverage: 46.31,
    quantitySold: 1,
    ordersCount: 1,
    grossRevenue: 46.31,
    totalSaleFees: 6.48,
    netRevenue: 39.83,
    proportionalShippingCost: 6.85,
    proportionalBillingCharges: 0,
    cmvUnit: 19.2,
    totalCogs: 19.2,
    totalCosts: 32.53,
    grossProfit: 20.63,
    grossMarginPercent: 44.55,
    netProfit: 11.93,
    netMarginPercent: 25.76,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB4960738705',
    itemId: null,
    title: 'Kit 3 Pares Meia Soquete Cano Curto Confortável Cor Sortida',
    pictureUrl: null,
    unitPriceAverage: 16.06,
    quantitySold: 4,
    ordersCount: 2,
    grossRevenue: 64.24,
    totalSaleFees: 4.5,
    netRevenue: 59.74,
    proportionalShippingCost: 27.64,
    proportionalBillingCharges: 0,
    cmvUnit: 3.12,
    totalCogs: 12.48,
    totalCosts: 44.62,
    grossProfit: 47.26,
    grossMarginPercent: 73.57,
    netProfit: 17.05,
    netMarginPercent: 26.54,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB4899182495',
    itemId: null,
    title: 'Calça Moletom Plus Size Masculina Flanelada Com Bolsos',
    pictureUrl: null,
    unitPriceAverage: 60.36,
    quantitySold: 3,
    ordersCount: 3,
    grossRevenue: 181.09,
    totalSaleFees: 29.17,
    netRevenue: 151.92,
    proportionalShippingCost: 24.85,
    proportionalBillingCharges: 0,
    cmvUnit: 33.05,
    totalCogs: 99.15,
    totalCosts: 153.17,
    grossProfit: 52.77,
    grossMarginPercent: 29.14,
    netProfit: 20.68,
    netMarginPercent: 11.42,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB7526690046',
    itemId: null,
    title:
      'Kit 10 Cueca Box Masculina Uomo Adulto Elástico Várias Cores Diversos P/M',
    pictureUrl: null,
    unitPriceAverage: 90.0,
    quantitySold: 1,
    ordersCount: 1,
    grossRevenue: 90.0,
    totalSaleFees: 12.6,
    netRevenue: 77.4,
    proportionalShippingCost: 14.45,
    proportionalBillingCharges: 0,
    cmvUnit: 38.5,
    totalCogs: 38.5,
    totalCosts: 65.55,
    grossProfit: 38.9,
    grossMarginPercent: 43.22,
    netProfit: 20.85,
    netMarginPercent: 23.17,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB7177391848',
    itemId: null,
    title: 'Calça Moletom Masculina Flanelada Com Bolso Confortável',
    pictureUrl: null,
    unitPriceAverage: 58.68,
    quantitySold: 11,
    ordersCount: 9,
    grossRevenue: 645.51,
    totalSaleFees: 103.23,
    netRevenue: 542.28,
    proportionalShippingCost: 88.95,
    proportionalBillingCharges: 28.59,
    cmvUnit: 26.9,
    totalCogs: 295.9,
    totalCosts: 516.67,
    grossProfit: 246.38,
    grossMarginPercent: 38.17,
    netProfit: 131.61,
    netMarginPercent: 20.39,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB7170820506',
    itemId: null,
    title: 'Camiseta Masculina Mormaii Original 100% Algodão Premium',
    pictureUrl: null,
    unitPriceAverage: 55.81,
    quantitySold: 71,
    ordersCount: 69,
    grossRevenue: 3962.74,
    totalSaleFees: 698.12,
    netRevenue: 3264.62,
    proportionalShippingCost: 699.14,
    proportionalBillingCharges: 341.93,
    cmvUnit: 27.99,
    totalCogs: 1987.29,
    totalCosts: 3726.48,
    grossProfit: 1277.33,
    grossMarginPercent: 32.23,
    netProfit: 419.68,
    netMarginPercent: 10.59,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB4960692551',
    itemId: null,
    title: 'Camiseta Masculina Mormaii Original 100% Algodão Premium',
    pictureUrl: null,
    unitPriceAverage: 50.88,
    quantitySold: 157,
    ordersCount: 146,
    grossRevenue: 7987.78,
    totalSaleFees: 923.94,
    netRevenue: 7063.84,
    proportionalShippingCost: 1363.03,
    proportionalBillingCharges: 0,
    cmvUnit: 27.99,
    totalCogs: 4394.43,
    totalCosts: 6681.4,
    grossProfit: 2669.41,
    grossMarginPercent: 33.42,
    netProfit: 986.87,
    netMarginPercent: 12.35,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
  {
    itemFullId: 'MLB5096230173',
    itemId: null,
    title:
      'Kit 4 Top Feminino Sutia Sem Costura Preto Bojo Sustentação Preto P/M',
    pictureUrl: null,
    unitPriceAverage: null,
    quantitySold: 0,
    ordersCount: 0,
    grossRevenue: 0,
    totalSaleFees: 0,
    netRevenue: 0,
    proportionalShippingCost: 0,
    proportionalBillingCharges: 0,
    // CMV conhecido (R$ 38,40) mesmo sem venda válida no período: 1 pedido
    // cancelado (R$ 87,87) foi excluído antes dos cálculos.
    cmvUnit: 38.4,
    totalCogs: 0,
    totalCosts: 0,
    grossProfit: 0,
    grossMarginPercent: 0,
    netProfit: 0,
    netMarginPercent: 0,
    lastSaleAtUtc: null,
    firstSaleAtUtc: null,
  },
];

const MOCK_SUMMARY: MercadoLivreAnalysisSummary = {
  ordersCount: 236,
  ordersPaidCount: 236,
  ordersShippedCount: 236,
  totalUnitsSold: 253,
  distinctProductsCount: 11,
  productsWithCmvCount: 11,
  productsWithoutCmvCount: 0,

  grossRevenue: 13173.51,
  totalSaleFees: 1810.56,
  netRevenue: 11362.95,

  totalShippingCost: 0,
  totalShippingCostFromApi: 2343.42,
  shipmentsResolvedCount: 236,
  shipmentsMissingCount: 0,

  totalBillingCharges: 370.52,
  billingRecordsConsumed: 2,
  billingOrdersMatched: 2,

  totalCogs: 6930.04,
  totalAllCosts: 11610.94,

  grossProfit: 4432.91,
  grossMarginPercent: 33.65,

  netProfit: 1562.57,
  netMarginPercent: 11.86,
};

/** Resposta fictícia completa, no formato devolvido pela API real. */
export const MOCK_PROFITABILITY_ANALYSIS: MercadoLivreTopProductsAnalysisResponse =
  {
    storeId: 'mock-store-daniel',
    mercadoLivreSellerId: 0,
    days: 31,
    fromUtc: '2026-08-01T00:00:00Z',
    toUtc: '2026-08-31T23:59:59Z',
    summary: MOCK_SUMMARY,
    topProducts: MOCK_PRODUCTS,
  };
